/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import bench.BenchmarkResult;
import bench.QueryExecution;
import cli.Run;
import com.hp.hpl.jena.sparql.engine.binding.Binding;
import java.io.File;
import java.io.PrintWriter;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import join.JoinOps;
import utils.QueryParser;
import utils.SplitQuery;

/**
 *
 * @author user
 */
public class RunFormRespaldo extends javax.swing.JFrame {

    DefaultTableModel tabla_Resultados = new DefaultTableModel();
    String[][] matriz_Resultados;
    /**
     * Creates new form RunForm
     */
    public RunFormRespaldo() {
        initComponents();
        cargarComboConsultas();
        cargarComboEndpoints();        
        cargarComboEstrategias();
        this.setTitle("Sparql_Strategies");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmb_Strategy = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Query = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btn_Run = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_Consulta = new javax.swing.JTextField();
        btn_Cerrar = new javax.swing.JButton();
        txt_Strategy = new javax.swing.JTextField();
        btn_Strategy = new javax.swing.JButton();
        cmb_Consulta = new javax.swing.JComboBox();
        btn_Consulta = new javax.swing.JButton();
        cmb_Endpoint = new javax.swing.JComboBox();
        txt_Endpoint = new javax.swing.JTextField();
        btn_Endpoint = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_Results = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txt_Browse = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Browse = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        txt_XML = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        txt_JSON = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        txt_CSV = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel4.setText("   Strategy:");

        cmb_Strategy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_Strategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_StrategyActionPerformed(evt);
            }
        });

        txt_Query.setColumns(20);
        txt_Query.setRows(5);
        txt_Query.setText("select ?s ?x\nwhere{\nSERVICE <http://190.15.141.66:8890/sparql/>{\n?s a <http://xmlns.com/foaf/0.1/Person>}\nSERVICE <http://190.15.141.66:8890/sparql/>{\n    ?x a <http://xmlns.com/foaf/0.1/Person>\n}\n}\nlimit 10");
        jScrollPane1.setViewportView(txt_Query);

        jLabel5.setText("Query:");

        btn_Run.setText("Run");
        btn_Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RunActionPerformed(evt);
            }
        });

        jLabel6.setText("   Consulta:");

        txt_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ConsultaActionPerformed(evt);
            }
        });

        btn_Cerrar.setText("Cerrar");
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });

        txt_Strategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_StrategyActionPerformed(evt);
            }
        });

        btn_Strategy.setText("√");
        btn_Strategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StrategyActionPerformed(evt);
            }
        });

        cmb_Consulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_Consulta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_ConsultaItemStateChanged(evt);
            }
        });
        cmb_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ConsultaActionPerformed(evt);
            }
        });

        btn_Consulta.setText("√");
        btn_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultaActionPerformed(evt);
            }
        });

        cmb_Endpoint.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_Endpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_EndpointActionPerformed(evt);
            }
        });

        txt_Endpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EndpointActionPerformed(evt);
            }
        });

        btn_Endpoint.setText("√");
        btn_Endpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EndpointActionPerformed(evt);
            }
        });

        jLabel7.setText("   Endpoint:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(68, 68, 68)
                                    .addComponent(btn_Run, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87)
                                    .addComponent(btn_Cerrar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(98, 98, 98)
                                            .addComponent(cmb_Strategy, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt_Strategy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_Strategy))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cmb_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_Consulta))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cmb_Endpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_Endpoint))
                                    .addComponent(txt_Endpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(136, 136, 136))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmb_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Consulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Endpoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Endpoint)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Endpoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Strategy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btn_Strategy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Strategy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Run)
                    .addComponent(btn_Cerrar))
                .addGap(25, 25, 25))
        );

        jTabbedPane3.addTab("Datos", jPanel2);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        txt_Results.setColumns(20);
        txt_Results.setRows(5);
        jScrollPane5.setViewportView(txt_Results);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Results", jPanel10);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        txt_Browse.setColumns(20);
        txt_Browse.setRows(5);
        jScrollPane12.setViewportView(txt_Browse);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Browse_Archivo", jPanel4);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tbl_Browse.setModel(tabla_Resultados);
        jScrollPane2.setViewportView(tbl_Browse);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Browse_Table", jPanel8);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        txt_XML.setColumns(20);
        txt_XML.setRows(5);
        jScrollPane13.setViewportView(txt_XML);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("XML", jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        txt_JSON.setColumns(20);
        txt_JSON.setRows(5);
        jScrollPane14.setViewportView(txt_JSON);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("JSON", jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        txt_CSV.setColumns(20);
        txt_CSV.setRows(5);
        jScrollPane15.setViewportView(txt_CSV);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("CSV", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane5)
                    .addComponent(jTabbedPane3))
                .addGap(0, 40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RunActionPerformed

        txt_Results.setText(null);
        txt_Browse.setText(null);
        txt_XML.setText(null);
        txt_JSON.setText(null);
        txt_CSV.setText(null);
        
        if(!validaVacio(txt_Consulta.getText(), "Consulta"))
            return;
        if(!validaVacio(txt_Endpoint.getText(), "Endpoint"))
            return;
        if(!validaVacio(txt_Strategy.getText(), "Strategy"))
            return;
                
        String[] joins = {txt_Strategy.getText()};
               
	System.out.println("Joins "+Arrays.toString(joins));
        txt_Results.append("Joins "+Arrays.toString(joins));              
        txt_Results.append(System.getProperty("line.separator"));   // Salto de línea 
        
	String localEndpoint = txt_Endpoint.getText();                
               
	boolean debug = false;
        int batch = -1;
	Run run = new Run();

        run.runQuery(txt_Query.getText(), joins, localEndpoint,debug, batch);
                  
        txt_Results.append(run.getTexto_Results().getText());
        txt_Browse.append(run.getTexto_Browse().getText());
        
        separarResultados(txt_Browse.getText());        
        datosTabla();

/*                        
        txt_Results.setText(null);
        txt_Browse.setText(null);
        txt_XML.setText(null);
        txt_JSON.setText(null);
        txt_CSV.setText(null);
        
        if(!validaVacio(txt_Consulta.getText(), "Consulta"))
            return;
        if(!validaVacio(txt_Endpoint.getText(), "Endpoint"))
            return;
        if(!validaVacio(txt_Strategy.getText(), "Strategy"))
            return;
                
        String[] joins = {txt_Strategy.getText()};
               
	System.out.println("Joins "+Arrays.toString(joins));
        txt_Results.append("Joins "+Arrays.toString(joins));              
        txt_Results.append(System.getProperty("line.separator"));   // Salto de línea 
        
        File outDir = new File("test.outdir");
	if (!outDir.exists())
            outDir.mkdirs();
		        
	String localEndpoint = txt_Endpoint.getText();                
        String pathConsulta = "resources/bio/" + txt_Consulta.getText();
        File subQueries = new File(pathConsulta);
               
	boolean debug = false;
        int batch = -1;
	Run run = new Run();

        if(subQueries.isDirectory()){
            for(File q : subQueries.listFiles()){
		if(q.isFile()){
                    run.runQuery(q, joins, localEndpoint,outDir,debug, batch);
		}
            }
	}else{
            run.runQuery(subQueries, joins, localEndpoint,outDir,debug, batch);
	}        
                  
        txt_Results.append(run.getTexto_Results().getText());
        txt_Browse.append(run.getTexto_Browse().getText());
        
        separarResultados(txt_Browse.getText());        
        datosTabla();
*/                
    }//GEN-LAST:event_btn_RunActionPerformed

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_CerrarActionPerformed

    private void txt_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ConsultaActionPerformed

    private void txt_StrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_StrategyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_StrategyActionPerformed

    private void txt_EndpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EndpointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EndpointActionPerformed

    private void btn_StrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StrategyActionPerformed
        // TODO add your handling code here:
        txt_Strategy.setText(cmb_Strategy.getSelectedItem().toString());        
    }//GEN-LAST:event_btn_StrategyActionPerformed

    private void btn_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultaActionPerformed
        // TODO add your handling code here:
        txt_Consulta.setText(cmb_Consulta.getSelectedItem().toString());
    }//GEN-LAST:event_btn_ConsultaActionPerformed

    private void btn_EndpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EndpointActionPerformed
        // TODO add your handling code here:
        txt_Endpoint.setText(cmb_Endpoint.getSelectedItem().toString());        
    }//GEN-LAST:event_btn_EndpointActionPerformed

    private void cmb_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ConsultaActionPerformed
        // TODO add your handling code here:
        txt_Consulta.setText("");        
    }//GEN-LAST:event_cmb_ConsultaActionPerformed

    private void cmb_EndpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_EndpointActionPerformed
        // TODO add your handling code here:
        txt_Endpoint.setText("");        
    }//GEN-LAST:event_cmb_EndpointActionPerformed

    private void cmb_StrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_StrategyActionPerformed
        // TODO add your handling code here:
        txt_Strategy.setText("");        
    }//GEN-LAST:event_cmb_StrategyActionPerformed

    private void cmb_ConsultaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_ConsultaItemStateChanged
        // TODO add your handling code here:        
    }//GEN-LAST:event_cmb_ConsultaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunFormRespaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunFormRespaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunFormRespaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunFormRespaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RunFormRespaldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_Consulta;
    private javax.swing.JButton btn_Endpoint;
    private javax.swing.JButton btn_Run;
    private javax.swing.JButton btn_Strategy;
    private javax.swing.JComboBox cmb_Consulta;
    private javax.swing.JComboBox cmb_Endpoint;
    private javax.swing.JComboBox cmb_Strategy;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable tbl_Browse;
    private javax.swing.JTextArea txt_Browse;
    private javax.swing.JTextArea txt_CSV;
    private javax.swing.JTextField txt_Consulta;
    private javax.swing.JTextField txt_Endpoint;
    private javax.swing.JTextArea txt_JSON;
    private javax.swing.JTextArea txt_Query;
    private javax.swing.JTextArea txt_Results;
    private javax.swing.JTextField txt_Strategy;
    private javax.swing.JTextArea txt_XML;
    // End of variables declaration//GEN-END:variables

public void cargarComboConsultas(){
    cmb_Consulta.removeAllItems();
    cmb_Consulta.addItem("b12.rq");
    cmb_Consulta.addItem("b13.rq");    
    txt_Consulta.setText(cmb_Consulta.getItemAt(0).toString());
}

public void cargarComboEndpoints(){
    cmb_Endpoint.removeAllItems();
    cmb_Endpoint.addItem("http://190.15.141.66:8890/sparql/");
    cmb_Endpoint.addItem("http://mgi.bio2rdf.org/sparql/");
    cmb_Endpoint.addItem("http://hgnc.bio2rdf.org/sparql/");
    txt_Endpoint.setText(cmb_Endpoint.getItemAt(0).toString());    
}

public void cargarComboEstrategias(){
    cmb_Strategy.removeAllItems();
    cmb_Strategy.addItem("VALUES");
    cmb_Strategy.addItem("UNION");
    cmb_Strategy.addItem("SERVICE");
    cmb_Strategy.addItem("FILTER");
    cmb_Strategy.addItem("NESTED");
    cmb_Strategy.addItem("SYMHASH");
    cmb_Strategy.addItem("SYMHASHP");
    txt_Strategy.setText(cmb_Strategy.getItemAt(0).toString());    
}

public boolean validaVacio(String campo, String nombreCampo){
    if(campo==null || campo.equals("")){
        JOptionPane.showMessageDialog(null, "Campo: " + nombreCampo + ", esta vacío");     
        return false;
    }else{
        return true;
    }
}

public void separarResultados(String resultados){
    matriz_Resultados = null;
    
    String[] filas_Resultados = resultados.split("->");    
    if(filas_Resultados.length==0)
        return;
    
    String[] datos_Fila = filas_Resultados[1].split("\\)");    
    if(datos_Fila.length==0)
        return;

    int numero_Filas = filas_Resultados.length;
    int numero_Columnas = datos_Fila.length;    
    System.out.println("filas: " + numero_Filas);
    System.out.println("columnas: " + numero_Columnas);
    
    matriz_Resultados = new String[numero_Filas-1][numero_Columnas-1]; 
        
    for(int i=1; i<filas_Resultados.length; i++){        
        String[] columnas_Resultados = filas_Resultados[i].split("\\)");
        for(int i1=0; i1<columnas_Resultados.length-1; i1++){
            matriz_Resultados[i-1][i1] = columnas_Resultados[i1];
            txt_XML.append(i1 + ": " + columnas_Resultados[i1]);
            txt_XML.append(System.getProperty("line.separator"));   // Salto de línea             
        }
    }    
}

public void datosTabla(){        
    txt_XML.append("MATRIZ ");
    txt_XML.append(System.getProperty("line.separator"));   // Salto de línea             
    
    tabla_Resultados.setNumRows(matriz_Resultados.length);
    
//    for(int j=0; j<matriz_Resultados[0].length; j++){
    for(int j=matriz_Resultados[0].length-1; j>=0; j--){    
        String nombreColumna = obtenerNombreColumna(matriz_Resultados[0][j]);
        tabla_Resultados.addColumn(nombreColumna);        
    }
        
    for(int i=0; i<matriz_Resultados.length; i++){        
        int contadorColumnas=0;
//        for(int j=0; j<matriz_Resultados[0].length; j++){
        for(int j=matriz_Resultados[0].length-1; j>=0; j--){                
            String respuesta = obtenerURI(matriz_Resultados[i][j]);
            tabla_Resultados.setValueAt(respuesta, i, contadorColumnas);
            contadorColumnas++;
        }
    }
    
}

public String obtenerURI(String respuesta){    
    try{
        String[] parte1 = respuesta.split("<");            
        String[] parte2 = parte1[1].split(">");
        String URI = parte2[0];
        return URI;
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Error al obtener la URI");                     
        return respuesta;
    }            
}

public String obtenerNombreColumna(String respuesta){    
    try{
        String[] parte1 = respuesta.split("\\?");            
        String[] parte2 = parte1[1].split("=");
        String nombreColumna = parte2[0];
        return nombreColumna;
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Error al obtener el nombre de la Columna");                     
        return respuesta;
    }            
}

}
